# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'img/blog'
public_folder: 'blog'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'J-son', name: 'json-post', widget: 'hidden', default: 'true' }
      - { label: 'Fecha', name: 'date', widget: 'datetime' }
      - { label: 'Meta Title', name: 'title', widget: 'string' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - { label: 'H1', name: 'h1', widget: 'string' }
      - { label: 'Image', name: 'avif', widget: 'image' }
      - { label: 'Alt', name: 'alt', widget: 'string' }
      - { label: 'URL', name: 'permalink', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'verticales'
    label: 'Verticales'
    folder: '_ciudades/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'ciudades' }
      - { label: 'CTA botón', name: 'boton1', widget: 'hidden', default: 'Ver las escuelas' }
      - { label: 'Enlace', name: 'boton1_url', widget: 'hidden', default: 'escuelas' }
      - { label: 'CTA2 botón', name: 'boton2', widget: 'hidden', default: 'Consejos para escoger' }
      - { label: 'Enlace2', name: 'boton2_url', widget: 'hidden', default: 'consejos' }
      - { label: 'Meta Title', name: 'title', widget: 'string' }
      - { label: 'Meta Description', name: 'description', widget: 'string' }
      - { label: 'H1', name: 'h1', widget: 'string' }
      - { label: 'Estado', name: 'category', widget: 'string' }
      - { label: 'Ciudad', name: 'ciudad', widget: 'string' }
      - { label: 'Image Avif', name: 'avif', widget: 'image' }
      - { label: 'Introducción', name: 'intro', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
